// Target state shape for the v8 Module + GameState migration.
// Runtime globals are being moved here in phases so each extraction stays safe.
export const STAGE_TRANSIENT_BATTLE_ARRAYS = [
  'enemies',
  'projectiles',
  'bombs',
  'particles',
  'groundFx',
  'beamFx',
  'damageNumbers',
  'healFx',
];

export function createArenaState(){
  return {
    phase: 'build',
    round: 1,
    buildTimer: 0,
    buildTimerMax: 0,
    cells: {},
    king: null,
    pickerOpen: false,
    pickerCell: null,
    pickerScroll: 0,
    managePanelCell: null,
    waveSpawnQueue: [],
    waveSpawnTimer: 0,
    waveSpawnBatchMode: false,
    waveSpawnBatchIndex: 0,
    wavePreview: '',
    waveThreats: null,
    waveMechanic: null,
    waveMechanicAssigned: false,
    bloodlustUsed: false,
    tranquilityUsed: false,
    bloodlustTimer: 0,
    tranquilityTimer: 0,
    tranquilityTickAcc: 0,
    spellUsed: [],
    _bloodlustRect: null,
    _tranquilityRect: null,
    rift: null,
    scheduledRiftRound: null,
    riftFiredThisRound: false,
    waveElapsed: 0,
    beacons: [],
    pauseMenu: false,
    _pauseBtnRect: null,
  };
}

export function createGameState(){
  return {
    screen: 'menu',
    progress: {
      maxStage: 1,
      stageStars: {},
      selectedDeck: [0,1,2,3,4,5],
      selectedSpells: [0,1],
      beans: 0,
      unlockedPerks: ['openingLedger'],
      selectedPerks: ['openingLedger'],
      defeatedBosses: [],
    },
    economy: {
      crystal: 5,
      maxCrystal: 10,
      gold: 0,
      stageGold: 0,
    },
    battle: {
      units: [],
      enemies: [],
      projectiles: [],
      particles: [],
      damageNumbers: [],
      healFx: [],
      bombs: [],
      groundFx: [],
      beamFx: [],
    },
    combatRuntime: {
      frame: 0,
      crystalRegenTimer: 0,
      combatStats: null,
    },
    environment: {
      weatherParticles: { raindrops: [], snowflakes: [], fogParticles: [], sandParticles: [] },
    },
    arena: createArenaState(),
    layout: {
      canvasDpr: 1,
      width: 500,
      height: 1000,
      arenaTop: 0,
      arenaBottom: 820,
      deployTop: 710,
      heroButton: { x: 456, y: 954, r: 30 },
      gridX: 0,
      gridW: 0,
      cellW: 0,
      gridY: 200,
      cellH: 70,
    },
    campaign: {
      currentStage: null,
      currentStageIdx: 0,
      playerCastle: null,
      enemyCastle: null,
      bossRef: null,
      bossWarning: 0,
      bossSpawned: false,
      waveTimer: 0,
      waveIdx: 0,
      stageTime: 0,
      waveWarnedIdx: 0,
      eliteSpawned: false,
      castleSpawnTimer: 0,
      stageOver: false,
      stageWon: false,
      stageStartTimer: 0,
      crystalNodes: [],
      towers: [],
    },
    squad: {
      unitLevels: new Array(14).fill(1),
      vodkaLevel: 1,
      cardHand: [],
      vodkaUnit: null,
      vodkaDeployCD: 0,
      vodkaDead: false,
      vodkaRespawn: 0,
      deckPickStage: [],
      spellPickStage: [],
      abilityCooldowns: [0,0],
      abilityUsed: [false,false],
    },
    ui: {
      selectedCard: -1,
      stageSelectScroll: 0,
      deckPickScroll: 0,
      spellPickScroll: 0,
      perkPickScroll: 0,
      codexOpen: false,
      codexScroll: 0,
      codexUnit: -1,
      levelEditOpen: false,
      abilityTargeting: -1,
      screenShake: 0,
      flashText: '',
      flashTimer: 0,
      flashColor: '#fff',
      signatureBanner: null,
      touchStartY: 0,
      touchAccumY: 0,
    },
  };
}
